language: python
python:
     - "3.4"
before_install:
    - apt-get update
    - apt-get -y install python3-pip python-dev
    - pip3 install -U setuptools
    - pip3 install -U virtualenvwrapper
    - python3 -V
    - pip3 -V

install:
     - pip3 install -r requirements.txt

script:
     - tests/test.py
