language: python
python:
     - "3.4"
before_install:
    - python3 -V
    - sudo apt-get update
    - sudo apt-get install python3-setuptools
    - sudo easy_install3 pip

install:
     - sudo pip3 install -r requirements.txt

script:
     - tests/test.py
